spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huiye86/sp-config
          search-paths: config
          #username: your-username
          #password: your-password
server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
