spring:
  application:
    name: eureka-server

server:
  port: 2001

eureka:
  server:
    enable-self-preservation: false #关闭保护模式
  client:
    #单台服务器，不向自己注册，不从自己拉取
    register-with-eureka: false
    fetch-registry: false